### ISSUE TITLE
toolbar title text in the center

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#11]
I want to show the toolbar title text in the center. And I want to change the text for tabs recent and contacts. So can you please suggest how to achieve the same?

**Comment by jitvarpatil** [comment]
Hi @imdBhargav 

You can follow the below link to move the Toolbar title in the center:
https://stackoverflow.com/questions/26533510/android-toolbar-center-title-and-custom-font

Also, To change the text for Tabs you can change it from CometChat admin panel or by modifying the code in ReadyUI source.

1]Using Admin Panel:

In CometChat Admin Panel go to Localize->Edit language->Mobile App, In Mobile App, you will find the option to update Contact, Recent, Groups Text 

For more information, you can refer our documentation at the following link: 

   https://docs.cometchat.com/admin-panel/language/

2] Using ReadyUI source:

In Cometchat Activity, You will find a method setupTabs which has Strings recentTabText,contactTabText,groupTabText, You can change the value to this strings to you requirment.

Feel free to contact us for further queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
Thanks for your response.

I am not using ReadyUI source I am using the SDK UI by addding dependency.
I will check the admin panel solution and let you know if it helps

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 
I have tried the admin panel solution that you provided above but not helped.

**Comment by jitvarpatil** [comment]
Hi @imdBhargav,

We have tested and the langs are getting changed on mobile platforms. It may take some time to reflect on the client front end because of our caching mechanism. Following is the screenshot of where you need to make changes on the Admin Panel.

![screen shot 2018-12-10 at 4 13 00 pm](https://user-images.githubusercontent.com/18652749/49727876-53bda980-fc97-11e8-8749-beaf2f92ad4e.png)
In the above image we have changed contact and groups langs and the successfully reflected in the mobile platforms. You can refer the screenshot below.

![device-2018-12-10-164700](https://user-images.githubusercontent.com/18652749/49729364-55896c00-fc9b-11e8-856d-42fcd8b1a6f2.png)

Feel free to contact us if you have any other queries.

**Comment by imdBhargav** [comment]
Hi @jitvarpatil 

Thanks for your solution. I have made appropriate changes from backend and waiting for reflect on Mobile.Once done let you know

Thanks
