### ISSUE TITLE
No Record Audio Option

### ISSUE THREAD

**Issue by imdBhargav** [cometchat-go/android-chat-sdk-demo#29]
Hello,

I can not see the record audio option in Chat screen. While it is available in IOS.

**Comment by mehtanishant** [comment]
Hello @imdBhargav,

Thank you for reporting the issue. We have tested this and we found that since the share voice note feature is disabled from your CometChat Administration Panel, it is not showing in the Chat Screen. If you want to use the feature you can enable it from CometChat Administration Panel > Features > Share Voice Note.

Feel free to contact us if you have any other queries.
